### PR TITLE
FIX register form policyId and amount field error

### PR DESCRIPTION
**Pull request by cnych**
fix register page policyId is optional on `Register IP Asset form`.

fix register page amount should number, but received string on  `Mint License NFT form`.

### CODE REVIEW

**Review by allenchuang — CHANGES_REQUESTED** [review]
Thanks for contributing, I think we also need to update the type check for zod on L18 to be string. Other than that it looks good!

**Comment by cnych** [comment]
> Thanks for contributing, I think we also need to update the type check for zod on L18 to be string. Other than that it looks good!

L18 is `amount: z.bigint(),`, need update amount to string type? Is the type received by the background string? Normally it should be int, right?

**Comment by allenchuang** [comment]
You're right in that it should be `int`. But the input field that is dynamically generated by default takes type `string` we will have to convert and parse to `BigInt` once submitted.

**Comment by cnych** [comment]
> You're right in that it should be `int`. But the input field that is dynamically generated by default takes type `string` we will have to convert and parse to `BigInt` once submitted.

I see, has update the amount type to string.

**Review by allenchuang — APPROVED** [review]
Lgtm

**Pull request merged**
